import {test,expect} from '@playwright/test';
import {mkdirSync} from 'node:fs';
async function boot(page){await page.goto('/');await expect(page.locator('#canvas .scene-svg')).toBeVisible();}
async function api(page,operation,parameters={},expected=null){return page.evaluate(async({operation,parameters,expected})=>{const session=await(await fetch('/api/session')).json();const response=await fetch('/api/call',{method:'POST',headers:{'Content-Type':'application/json','x-sequencewright-csrf':session.csrf},body:JSON.stringify({operation,parameters,expected,key:crypto.randomUUID()})});const body=await response.json();if(!body.ok)throw new Error(body.error.message);return body.data;},{operation,parameters,expected});}
async function isolated(page,title){await boot(page);const ws=await api(page,'project.list');const made=await api(page,'project.create',{title,template:'product'},ws.version);await page.evaluate(resource=>localStorage.setItem('sw:project',resource),made.metadata.created.resource);await page.reload();await expect(page.locator('.project-title')).toContainText(title);return made.metadata.created.resource;}
const workspace=async(page,name)=>{await page.getByRole('navigation',{name:'Workspaces'}).getByRole('button',{name,exact:true}).click();};

test('original studies and all workspaces are navigable',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await boot(page);
 for(const name of ['Brief','Narrative','Storyboard','Alternatives','Changes','Dependencies','Review','Deliver','Canvas'])await workspace(page,name);
 await expect(page.locator('#canvas')).toBeVisible();expect(errors).toEqual([]);
});
test('editing text persists through reload',async({page})=>{
 await isolated(page,'Text persistence');await page.locator('[data-action="inspector-layers"]').click();await page.locator('.layer-list').getByRole('button',{name:'Main statement',exact:true}).click();await page.locator('textarea[name="text"]').fill('A revision that lasts.');await page.getByRole('button',{name:'Apply object changes'}).click();await expect(page.locator('#canvas')).toContainText('A revision that lasts.');await page.reload();await expect(page.locator('#canvas')).toContainText('A revision that lasts.');
});
test('manual alternative is isolated until accepted',async({page})=>{
 const resource=await isolated(page,'Scoped proposal');await page.locator('[data-action="inspector-layers"]').click();await page.getByRole('button',{name:'Main statement',exact:true}).click();await workspace(page,'Alternatives');await page.getByRole('button',{name:'Create an alternative'}).click();const modal=page.locator('#modal');await modal.getByLabel('Alternative text',{exact:true}).fill('The other direction.');await modal.getByLabel('Why this change?').fill('Compare a more direct statement.');await modal.getByRole('button',{name:'Save proposal'}).click();await expect(modal).not.toBeVisible();let doc=(await api(page,'document.read',{resource})).document;expect(doc.scenes[0].objects[1].text).not.toBe('The other direction.');await page.getByRole('button',{name:'Compare A / B'}).click();await expect(page.locator('#modal .compare-grid')).toContainText('The other direction.');await page.locator('#modal [data-action="close-dialog"]').first().click();await page.getByRole('button',{name:'Accept proposal'}).click();await expect(page.locator('.proposal .badge')).toHaveText('applied');doc=(await api(page,'document.read',{resource})).document;expect(doc.scenes[0].objects[1].text).toBe('The other direction.');
});
test('brief and anchored comments save',async({page})=>{
 const resource=await isolated(page,'Editorial review');await workspace(page,'Brief');await page.getByLabel('Who is this for?').fill('Independent filmmakers');await page.getByRole('button',{name:'Save brief'}).click();await expect(page.getByLabel('Who is this for?')).toHaveValue('Independent filmmakers');await workspace(page,'Review');await page.getByRole('button',{name:'Add comment',exact:true}).click();await page.locator('#modal').getByLabel('Comment',{exact:true}).fill('Hold this beat a little longer.');await page.locator('#modal').getByRole('button',{name:'Add comment'}).click();await expect(page.locator('.workspace-page')).toContainText('Hold this beat a little longer.');const doc=(await api(page,'document.read',{resource})).document;expect(doc.reviews[0].revision).toBeTruthy();expect(doc.brief.audience).toBe('Independent filmmakers');
});
test('branch creation preserves main and opens merge review',async({page})=>{
 const resource=await isolated(page,'Branch review');await workspace(page,'Changes');await page.getByRole('button',{name:'New branch',exact:true}).click();await page.locator('#modal').getByLabel('Branch name').fill('second-cut');await page.locator('#modal').getByRole('button',{name:'Create branch'}).click();await expect(page.getByLabel('Active branch')).toHaveValue(resource.replace('@main','@second-cut'));expect((await api(page,'document.read',{resource})).document.title).toBe('Branch review');await page.getByRole('button',{name:'Compare & merge'}).click();await expect(page.locator('#branch-comparison')).toContainText('Merge reviewed changes');
});
test('caption editing and source downloads do not claim media render',async({page})=>{
 await isolated(page,'Source delivery');await page.getByRole('button',{name:'Edit captions',exact:true}).click();await page.getByRole('button',{name:'Edit',exact:true}).first().click();await page.locator('#modal').getByLabel('Caption text').fill('An editable caption.');await page.locator('#modal button[type="submit"]').click();await expect(page.locator('.workspace-page')).toContainText('An editable caption.');await workspace(page,'Deliver');const download=page.waitForEvent('download');await page.getByRole('button',{name:'WebVTT captions'}).click();expect((await download).suggestedFilename()).toMatch(/\.vtt$/);await expect(page.locator('.workspace-page')).toContainText('not an MP4');await expect(page.locator('.integration-row .badge')).toHaveText(['Not connected','Not connected','Not connected','Not connected']);
});
test('stale editing cannot overwrite a concurrent change',async({page})=>{
 const resource=await isolated(page,'Concurrent editing');await page.getByRole('button',{name:'Scene',exact:true}).click();await page.locator('.inspector input[name="name"]').fill('My pending change');const before=await api(page,'document.read',{resource});await api(page,'scene.update',{sceneId:'s-1',changes:{name:'Change from another role'}},before.version);await page.getByRole('button',{name:'Apply scene changes'}).click();await expect(page.locator('.error-banner')).toBeVisible();expect((await api(page,'document.read',{resource})).document.scenes[0].name).toBe('Change from another role');await page.getByRole('button',{name:'Reload current revision'}).click();await expect(page.locator('.inspector input[name="name"]')).toHaveValue('Change from another role');
});
test('keyboard transport and command palette',async({page})=>{
 await isolated(page,'Keyboard editing');const before=await page.locator('#current-time').textContent();await page.keyboard.press('ArrowRight');await expect(page.locator('#current-time')).not.toHaveText(before);await page.keyboard.press('Control+k');await expect(page.locator('#modal')).toBeVisible();await page.getByLabel('Find a command').fill('captions');await page.locator('#modal').getByRole('button',{name:'Captions',exact:true}).click();await expect(page.getByRole('heading',{name:'Captions and timing'})).toBeVisible();
});
test('desktop light dark compact and mobile screenshot evidence',async({page})=>{
 await boot(page);mkdirSync('verification/browser',{recursive:true});await page.screenshot({path:'verification/browser/desktop-dark.png',fullPage:true});
 await page.locator('[data-action="theme"]').click();await expect(page.locator('html')).toHaveAttribute('data-theme','light');await page.screenshot({path:'verification/browser/desktop-light.png',fullPage:true});
 await page.setViewportSize({width:1024,height:800});await page.screenshot({path:'verification/browser/compact.png',fullPage:true});await page.setViewportSize({width:390,height:844});await expect(page.locator('#canvas')).toBeVisible();await page.screenshot({path:'verification/browser/mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
});
